04 oop_basic solution
js-tasks-ru/js-20200821-3_deepgmc pull request #4
Opened 2020-09-04 15:17 UTC by Deepgmc

успел до занятия, еще видимо предстоит рефакторить

2020-09-04 15:24 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-09-04 15:25 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    graphValue = 'def'
что означает `def` и почему это было здесь объявлено?

2020-09-04 15:26 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    getValue(){
почему предыдущие методы - это геттеры, а это обычная функция?

2020-09-04 15:27 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        return `<div class="${this.data.length > 0 ? 'column-chart' : 'column-chart_loading'}">
`this.data.length > 0` такие проверки принято сокращать: `this.data.length ? ... : ...`

2020-09-04 15:27 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.data.forEach((thisValue) => {
здесь можно избавиться от массива `bars` заменив `forEach` на `map`

2020-09-04 15:28 UTC, dosandk requested changes
необходимо внести правки согласно комментариям и ответить на вопросы

2020-09-05 10:55 UTC, Deepgmc commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    graphValue = 'def'
остался мусор после дебага, извиняюсь

2020-09-05 11:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-07 11:11 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    get href(){
геттеры `href`, `label` и `value` выглядят излишними. По сути они просто оборачивают какое-то свойство класса. Конкретно в нашем компоненте это не решает никакой проблемы и не добавляет удобства,  так делать не следует

2020-09-07 11:13 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    get tpl(){
`tpl` - не экономьте на названиях переменных и методов. Три символа эта та грань минимальной длины имени за которую не следует заходить. Я бы даже сказал что не следует именовать что-либо именами короче 3х символов.
имя `template` было бы гораздо понятнее

2020-09-07 11:14 UTC, dosandk approved these changes
решение принято, посмотрите комменты!

2020-09-07 11:14 UTC, merged